// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ParkingMaster",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ParkingMaster",
            targets: ["AppModule"],
            bundleIdentifier: "com.asher-appleDevAcademy.ParkingMaster",
            teamIdentifier: "9QKHF269WJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Unknown Usage Description"),
                .mediaLibrary(purposeString: "Unknown Usage Description")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/maxxfrazer/FocusEntity", "1.1.1"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FocusEntity", package: "focusentity")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)